neural_net:
    hidden_nodes_1: 256
    hidden_nodes_2: 256

agent:
    agent_type: "DQN_AGENT"
    max_grad_norm: 100
    gamma: 0.99
    tau: 0.005
    lr: 0.0001
    epsilon_start: 0.9
    epsilon_min: 0.05
    epsilon_decay: 1000
    replay_mem_size: 10_000
    weights_file: "weights/current.pt"

env:
    env_name: "CartPole-v1"
    num_update_target: 1
    num_save_weights: 50
    batch_size: 128
    train: true
    plot_training: true
    training_episodes: 1000
    validate: true
    plot_validation: true
    validating_episodes: 100
    logging_level: "INFO"
